_target_: src.models.prostate158_module.Prostate158LitModule

optimizer: null # fallback Novograd
#  optimizer:
#    _target_: torch.optim.AdamW
#    _partial_: true
#    lr: 0.001
#    weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: true
  max_lr: 0.001
  steps_per_epoch: 30
  epochs: 50 # adjust accordingly

ndim: 3
prostate_mode: both  # "anatomy", "tumor", "both"
channels: [ 16, 32, 64, 128, 256, 512 ]
strides: [ 2, 2, 2, 2, 2 ]
num_res_units: 4
act: PRELU
norm: BATCH
dropout: 0.15

# compile model for faster training with pytorch 2.0
compile: false
