# @package _global_

defaults:
  - _self_
  - data: anatomy # choose datamodule with `test_dataloader()` for evaluation
  - model: anatomy
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /scratch/users/gsoykan20/projects/prostate-158-improved/logs/train/runs/2024-05-31_11-54-46/checkpoints/last.ckpt
